name = "btb-worker"
main = "worker_full.js"
compatibility_date = "2025-09-25"
type = "javascript"

kv_namespaces = [
  { binding = "MEMORY_KV", id = "9a915108-7b9e-4562-9549-1e575a7fd412" },
  { binding = "JOBS_KV", id = "PASTE_JOBS_KV_ID" }
]
